MAIMPROGRAM _PROGR ;
START DATA INTEGER _VALUE , _RESUL , _CYCLE ;
  GET (_VALUE)
  _RESUL <- 1
  FOR  _CYCLE <- 0 TO 32767 DO
    IF ( _VALUE != 0 ) ; ELSE GOTO _ENDCY ;
     _RESUL <- _RESUL * _VALUE
     _VALUE <- _VALUE - 1
  ;
  _ENDCY :
  PUT ( _RESUL )
END
