MAIMPROGRAM _PROGR ;
START DATA INTEGER _AVVVVV , _BVVVVV , _CVVVVV ;
  GET _AVVVVV ;
  GET _BVVVVV ;
  GET _CVVVVV ;
  IF ( _AVVVVV = _BVVVVV ) ; ELSE GOTO _CALUET ;
    GOTO _BALUET ;
_CALUET :
  PUT ( 0 ) ;
  GOTO _ENASDF ;
_BALUET :
  IF ( _AVVVVV = _CVVVVV ) ; ELSE GOTO _CALUET ;
  PUT ( 1 ) ;
_ENASDF :
  GET _AVVVVV ;
END
